name: 'iFlow CLI Action'
description: 'Execute iFlow CLI commands in GitHub Actions workflows'
author: 'iflow-ai'
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  prompt:
    description: 'The prompt to execute with iFlow CLI'
    required: true
  api_key:
    description: 'iFlow API key for authentication'
    required: false
  settings_json:
    description: 'Complete iFlow settings.json content (JSON string). If provided, this will override other configuration options.'
    required: false
  base_url:
    description: 'Custom base URL for iFlow API'
    required: false
    default: 'https://apis.iflow.cn/v1'
  model:
    description: 'Model name to use'
    required: false
    default: 'Qwen3-Coder'
  working_directory:
    description: 'Working directory to run iFlow CLI from'
    required: false
    default: '.'
  timeout:
    description: 'Timeout for iFlow CLI execution in seconds (1-86400)'
    required: false
    default: "3600"  # Default to 1 hour
  extra_args:
    description: 'Additional command line arguments to pass to iFlow CLI (space-separated string)'
    required: false
    default: ''
  precmd:
    description: 'Shell command(s) to execute before running iFlow CLI (e.g., "npm install", "git fetch")'
    required: false
    default: ''
  gh_version:
    description: 'Version of GitHub CLI to install (e.g., "2.76.2"). If not specified, uses the pre-installed version.'
    required: false
    default: ''
  iflow_version:
    description: 'Version of iFlow CLI to install (e.g., "0.2.4"). If not specified, uses the pre-installed version.'
    required: false
    default: ''

outputs:
  result:
    description: 'Output from iFlow CLI execution'
  exit_code:
    description: 'Exit code from iFlow CLI execution'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/iflow-ai/iflow-cli-action:main'